# Generated by Django 5.0.1 on 2024-02-02 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("txtyaml", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
