# Generated by Django 5.0.1 on 2024-02-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("txtyaml", "0005_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="uploaded_at",
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="converted_yaml",
            field=models.TextField(blank=True, null=True),
        ),
    ]
