# Generated by Django 5.0.1 on 2024-02-02 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("txtyaml", "0006_remove_uploadedfile_uploaded_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadedFile",
        ),
    ]
