# Generated by Django 5.0.1 on 2024-02-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("txtyaml", "0008_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFileForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(max_length=255, upload_to="")),
            ],
        ),
    ]
